data class ViewState(
    val darkMode: Boolean = false,
    val appName: String = "",
    val packageName: String = "",
    val projectVersion: String = "1.0.0",
    val windowWidth: String = "800",
    val windowHeight: String = "600",
    val dependencies: Map<String, Boolean> = mapOf(
        "HotReload" to true,
        "Deskit" to true,
        "Retrofit" to false,
        "SQLDelight" to false,
        "Ktor" to false,
        "Decompose" to false,
        "ImageLoader" to false,
        "Precompose" to false,
        "Sentry" to false,
        "Markdown" to false,
        "KotlinxDatetime" to false
    ),
    val isGenerating: Boolean = false,
    val showPreview: Boolean = false,
    val showFileSaver: Boolean = false,
    val showSuccessDialog: Boolean = false,
    val showErrorDialog: Boolean = false,
    val packageNameError: String = "",
    val errorMessage: String = "",
    val successMessage: String = "",
    val suggestedFileName: String = ""
)